format_version: 10
pipelines:
  sewshul:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-589ea36:
        git: http://gitea-http.gitea.svc.cluster.local:3000/gitea-admin/sewshul.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - compile:
        fetch_materials: true
        keep_artifacts: true
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          compile-sewshul:
            elastic_profile_id: buildah
            timeout: 0
            artifacts:
            - build:
                source: sewshul
            tasks:
            - exec:
                arguments:
                  - -c
                  - ./compile.sh
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - find .
                command: /bin/bash
                run_if: passed
    - package:
        fetch_materials: true
        keep_artifacts: true
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          package-sewshul:
            elastic_profile_id: buildah
            timeout: 0
            artifacts:
            - build:
                source: build
            tasks:
            - fetch:
                pipeline: sewshul
                stage: compile
                job: compile-sewshul
                source: sewshul/
            - exec:
                arguments:
                  - -c
                  - buildah bud -t sewshul:${GO_PIPELINE_LABEL} -f Dockerfile .
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - mkdir build && cd build && buildah push sewshul:${GO_PIPELINE_LABEL} oci-archive:./sewshul.tar:sewshul:${GO_PIPELINE_LABEL}
                command: /bin/bash
                run_if: passed
    - push:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          push-sewshul:
            elastic_profile_id: buildah
            timeout: 0
            artifacts:
            tasks:
            - fetch:
                pipeline: sewshul
                stage: package
                job: package-sewshul
                source: build/
            - exec:
                arguments:
                  - -c
                  - buildah pull oci-archive:./build/sewshul.tar 
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - buildah login -u jstrohm -p ${DOCKER_PASSWORD} docker.io
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - buildah push sewshul:${GO_PIPELINE_LABEL} docker://jstrohm/sewshul:${GO_PIPELINE_LABEL}
                command: /bin/bash
                run_if: passed
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          push-sewshul:
            elastic_profile_id: kubectl
            timeout: 0
            artifacts:
            tasks:
            - exec:
                arguments:
                  - -c
                  - kubectl get pod -n default
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                  - -c
                  - kubectl set image deployment/sewshul sewshul=jstrohm/sewshul:${GO_PIPELINE_LABEL} -n default
                command: /bin/bash
                run_if: passed
