apiVersion: v1
kind: Service
metadata:
  name: login-{{ include "sewshul-chart.fullname" . }}
  labels:
    {{- include "sewshul-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.loginservice.type }}
  ports:
    - port: {{ .Values.loginservice.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sewshul-chart.selectorLabels" . | nindent 4 }}
