apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sewshul-chart.fullname" . }}
  labels:
    {{- include "sewshul-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "sewshul-chart.fullname" . }}
  endpoints:
    - port: http
      path: /metrics
