// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: proto/list.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SocialListType int32

const (
	SocialListType_FOLLOW  SocialListType = 0
	SocialListType_FRIEND  SocialListType = 1
	SocialListType_BLOCKED SocialListType = 2
)

// Enum value maps for SocialListType.
var (
	SocialListType_name = map[int32]string{
		0: "FOLLOW",
		1: "FRIEND",
		2: "BLOCKED",
	}
	SocialListType_value = map[string]int32{
		"FOLLOW":  0,
		"FRIEND":  1,
		"BLOCKED": 2,
	}
)

func (x SocialListType) Enum() *SocialListType {
	p := new(SocialListType)
	*p = x
	return p
}

func (x SocialListType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SocialListType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_list_proto_enumTypes[0].Descriptor()
}

func (SocialListType) Type() protoreflect.EnumType {
	return &file_proto_list_proto_enumTypes[0]
}

func (x SocialListType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SocialListType.Descriptor instead.
func (SocialListType) EnumDescriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{0}
}

type GetSocialListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string         `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ListType SocialListType `protobuf:"varint,2,opt,name=list_type,json=listType,proto3,enum=proto.SocialListType" json:"list_type,omitempty"`
}

func (x *GetSocialListRequest) Reset() {
	*x = GetSocialListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSocialListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSocialListRequest) ProtoMessage() {}

func (x *GetSocialListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSocialListRequest.ProtoReflect.Descriptor instead.
func (*GetSocialListRequest) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{0}
}

func (x *GetSocialListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSocialListRequest) GetListType() SocialListType {
	if x != nil {
		return x.ListType
	}
	return SocialListType_FOLLOW
}

type GetSocialListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Ids   []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetSocialListResponse) Reset() {
	*x = GetSocialListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_list_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSocialListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSocialListResponse) ProtoMessage() {}

func (x *GetSocialListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSocialListResponse.ProtoReflect.Descriptor instead.
func (*GetSocialListResponse) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{1}
}

func (x *GetSocialListResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetSocialListResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type AddToSocialListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         string         `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SocialListType SocialListType `protobuf:"varint,2,opt,name=social_list_type,json=socialListType,proto3,enum=proto.SocialListType" json:"social_list_type,omitempty"`
	IdToAdd        string         `protobuf:"bytes,3,opt,name=id_to_add,json=idToAdd,proto3" json:"id_to_add,omitempty"`
}

func (x *AddToSocialListRequest) Reset() {
	*x = AddToSocialListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_list_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToSocialListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToSocialListRequest) ProtoMessage() {}

func (x *AddToSocialListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToSocialListRequest.ProtoReflect.Descriptor instead.
func (*AddToSocialListRequest) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{2}
}

func (x *AddToSocialListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddToSocialListRequest) GetSocialListType() SocialListType {
	if x != nil {
		return x.SocialListType
	}
	return SocialListType_FOLLOW
}

func (x *AddToSocialListRequest) GetIdToAdd() string {
	if x != nil {
		return x.IdToAdd
	}
	return ""
}

type AddToSocialListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddToSocialListResponse) Reset() {
	*x = AddToSocialListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_list_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToSocialListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToSocialListResponse) ProtoMessage() {}

func (x *AddToSocialListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToSocialListResponse.ProtoReflect.Descriptor instead.
func (*AddToSocialListResponse) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{3}
}

func (x *AddToSocialListResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *AddToSocialListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveFromSocialListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         string         `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SocialListType SocialListType `protobuf:"varint,2,opt,name=social_list_type,json=socialListType,proto3,enum=proto.SocialListType" json:"social_list_type,omitempty"`
	IdToRemove     string         `protobuf:"bytes,3,opt,name=id_to_remove,json=idToRemove,proto3" json:"id_to_remove,omitempty"`
}

func (x *RemoveFromSocialListRequest) Reset() {
	*x = RemoveFromSocialListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_list_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFromSocialListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromSocialListRequest) ProtoMessage() {}

func (x *RemoveFromSocialListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromSocialListRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromSocialListRequest) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveFromSocialListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveFromSocialListRequest) GetSocialListType() SocialListType {
	if x != nil {
		return x.SocialListType
	}
	return SocialListType_FOLLOW
}

func (x *RemoveFromSocialListRequest) GetIdToRemove() string {
	if x != nil {
		return x.IdToRemove
	}
	return ""
}

type RemoveFromSocialListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RemoveFromSocialListResponse) Reset() {
	*x = RemoveFromSocialListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_list_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFromSocialListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromSocialListResponse) ProtoMessage() {}

func (x *RemoveFromSocialListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromSocialListResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromSocialListResponse) Descriptor() ([]byte, []int) {
	return file_proto_list_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveFromSocialListResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RemoveFromSocialListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_list_proto protoreflect.FileDescriptor

var file_proto_list_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x32,
	0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x4d, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64,
	0x73, 0x22, 0x8e, 0x01, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x53, 0x6f, 0x63, 0x69, 0x61,
	0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x10, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0e, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x09, 0x69, 0x64, 0x5f, 0x74, 0x6f, 0x5f,
	0x61, 0x64, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x64, 0x54, 0x6f, 0x41,
	0x64, 0x64, 0x22, 0x57, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x53, 0x6f, 0x63, 0x69, 0x61,
	0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x99, 0x01, 0x0a, 0x1b,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x10, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0e, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x69, 0x64, 0x5f, 0x74, 0x6f, 0x5f, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x64, 0x54,
	0x6f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x22, 0x5c, 0x0a, 0x1c, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x35, 0x0a, 0x0e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4c,
	0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x4f, 0x4c, 0x4c, 0x4f,
	0x57, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x52, 0x49, 0x45, 0x4e, 0x44, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x45, 0x44, 0x10, 0x02, 0x32, 0x92, 0x02, 0x0a,
	0x11, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x63, 0x69,
	0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50,
	0x0a, 0x0f, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x53,
	0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x53, 0x6f,
	0x63, 0x69, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x5f, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x6f,
	0x63, 0x69, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x6f, 0x63, 0x69, 0x61,
	0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x53,
	0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x68, 0x6f, 0x79, 0x6c, 0x65, 0x31, 0x39, 0x37, 0x34, 0x2f, 0x73, 0x65, 0x77, 0x73, 0x68, 0x75,
	0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_list_proto_rawDescOnce sync.Once
	file_proto_list_proto_rawDescData = file_proto_list_proto_rawDesc
)

func file_proto_list_proto_rawDescGZIP() []byte {
	file_proto_list_proto_rawDescOnce.Do(func() {
		file_proto_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_list_proto_rawDescData)
	})
	return file_proto_list_proto_rawDescData
}

var file_proto_list_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_list_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_list_proto_goTypes = []interface{}{
	(SocialListType)(0),                  // 0: proto.SocialListType
	(*GetSocialListRequest)(nil),         // 1: proto.GetSocialListRequest
	(*GetSocialListResponse)(nil),        // 2: proto.GetSocialListResponse
	(*AddToSocialListRequest)(nil),       // 3: proto.AddToSocialListRequest
	(*AddToSocialListResponse)(nil),      // 4: proto.AddToSocialListResponse
	(*RemoveFromSocialListRequest)(nil),  // 5: proto.RemoveFromSocialListRequest
	(*RemoveFromSocialListResponse)(nil), // 6: proto.RemoveFromSocialListResponse
	(*Error)(nil),                        // 7: proto.Error
}
var file_proto_list_proto_depIdxs = []int32{
	0, // 0: proto.GetSocialListRequest.list_type:type_name -> proto.SocialListType
	7, // 1: proto.GetSocialListResponse.error:type_name -> proto.Error
	0, // 2: proto.AddToSocialListRequest.social_list_type:type_name -> proto.SocialListType
	7, // 3: proto.AddToSocialListResponse.error:type_name -> proto.Error
	0, // 4: proto.RemoveFromSocialListRequest.social_list_type:type_name -> proto.SocialListType
	7, // 5: proto.RemoveFromSocialListResponse.error:type_name -> proto.Error
	1, // 6: proto.SocialListService.GetSocialList:input_type -> proto.GetSocialListRequest
	3, // 7: proto.SocialListService.AddToSocialList:input_type -> proto.AddToSocialListRequest
	5, // 8: proto.SocialListService.RemoveFromSocialList:input_type -> proto.RemoveFromSocialListRequest
	2, // 9: proto.SocialListService.GetSocialList:output_type -> proto.GetSocialListResponse
	4, // 10: proto.SocialListService.AddToSocialList:output_type -> proto.AddToSocialListResponse
	6, // 11: proto.SocialListService.RemoveFromSocialList:output_type -> proto.RemoveFromSocialListResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_list_proto_init() }
func file_proto_list_proto_init() {
	if File_proto_list_proto != nil {
		return
	}
	file_proto_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSocialListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_list_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSocialListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_list_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToSocialListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_list_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToSocialListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_list_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFromSocialListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_list_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFromSocialListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_list_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_list_proto_goTypes,
		DependencyIndexes: file_proto_list_proto_depIdxs,
		EnumInfos:         file_proto_list_proto_enumTypes,
		MessageInfos:      file_proto_list_proto_msgTypes,
	}.Build()
	File_proto_list_proto = out.File
	file_proto_list_proto_rawDesc = nil
	file_proto_list_proto_goTypes = nil
	file_proto_list_proto_depIdxs = nil
}
