// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: proto/mumble.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MumbleMurmer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId    string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Timestamp  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DistroList []string               `protobuf:"bytes,4,rep,name=distroList,proto3" json:"distroList,omitempty"`
	Data       []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Signature  []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *MumbleMurmer) Reset() {
	*x = MumbleMurmer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mumble_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MumbleMurmer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MumbleMurmer) ProtoMessage() {}

func (x *MumbleMurmer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mumble_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MumbleMurmer.ProtoReflect.Descriptor instead.
func (*MumbleMurmer) Descriptor() ([]byte, []int) {
	return file_proto_mumble_proto_rawDescGZIP(), []int{0}
}

func (x *MumbleMurmer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MumbleMurmer) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *MumbleMurmer) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MumbleMurmer) GetDistroList() []string {
	if x != nil {
		return x.DistroList
	}
	return nil
}

func (x *MumbleMurmer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MumbleMurmer) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type MurmerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *MumbleMurmer `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MurmerRequest) Reset() {
	*x = MurmerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mumble_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MurmerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MurmerRequest) ProtoMessage() {}

func (x *MurmerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mumble_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MurmerRequest.ProtoReflect.Descriptor instead.
func (*MurmerRequest) Descriptor() ([]byte, []int) {
	return file_proto_mumble_proto_rawDescGZIP(), []int{1}
}

func (x *MurmerRequest) GetData() *MumbleMurmer {
	if x != nil {
		return x.Data
	}
	return nil
}

type MurmerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MurmerResponse) Reset() {
	*x = MurmerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mumble_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MurmerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MurmerResponse) ProtoMessage() {}

func (x *MurmerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mumble_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MurmerResponse.ProtoReflect.Descriptor instead.
func (*MurmerResponse) Descriptor() ([]byte, []int) {
	return file_proto_mumble_proto_rawDescGZIP(), []int{2}
}

var File_proto_mumble_proto protoreflect.FileDescriptor

var file_proto_mumble_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x75, 0x6d, 0x62, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc5, 0x01, 0x0a,
	0x0c, 0x4d, 0x75, 0x6d, 0x62, 0x6c, 0x65, 0x4d, 0x75, 0x72, 0x6d, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x22, 0x38, 0x0a, 0x0d, 0x4d, 0x75, 0x72, 0x6d, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x75, 0x6d, 0x62,
	0x6c, 0x65, 0x4d, 0x75, 0x72, 0x6d, 0x65, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x10,
	0x0a, 0x0e, 0x4d, 0x75, 0x72, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0x46, 0x0a, 0x0d, 0x4d, 0x75, 0x6d, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x35, 0x0a, 0x06, 0x4d, 0x75, 0x72, 0x6d, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x75, 0x72, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x75, 0x72, 0x6d, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6f, 0x79, 0x6c, 0x65, 0x31, 0x39, 0x37, 0x34,
	0x2f, 0x73, 0x65, 0x77, 0x73, 0x68, 0x75, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_mumble_proto_rawDescOnce sync.Once
	file_proto_mumble_proto_rawDescData = file_proto_mumble_proto_rawDesc
)

func file_proto_mumble_proto_rawDescGZIP() []byte {
	file_proto_mumble_proto_rawDescOnce.Do(func() {
		file_proto_mumble_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mumble_proto_rawDescData)
	})
	return file_proto_mumble_proto_rawDescData
}

var file_proto_mumble_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_mumble_proto_goTypes = []interface{}{
	(*MumbleMurmer)(nil),          // 0: proto.MumbleMurmer
	(*MurmerRequest)(nil),         // 1: proto.MurmerRequest
	(*MurmerResponse)(nil),        // 2: proto.MurmerResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_proto_mumble_proto_depIdxs = []int32{
	3, // 0: proto.MumbleMurmer.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: proto.MurmerRequest.data:type_name -> proto.MumbleMurmer
	1, // 2: proto.MumbleService.Murmer:input_type -> proto.MurmerRequest
	2, // 3: proto.MumbleService.Murmer:output_type -> proto.MurmerResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_mumble_proto_init() }
func file_proto_mumble_proto_init() {
	if File_proto_mumble_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_mumble_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MumbleMurmer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mumble_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MurmerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mumble_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MurmerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mumble_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mumble_proto_goTypes,
		DependencyIndexes: file_proto_mumble_proto_depIdxs,
		MessageInfos:      file_proto_mumble_proto_msgTypes,
	}.Build()
	File_proto_mumble_proto = out.File
	file_proto_mumble_proto_rawDesc = nil
	file_proto_mumble_proto_goTypes = nil
	file_proto_mumble_proto_depIdxs = nil
}
